# Generated by Django 4.0.6 on 2022-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0009_alter_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
