# Generated by Django 4.0.6 on 2022-12-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0013_alter_cart_qty_alter_cart_sum_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='menu',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myorder.cart'),
        ),
    ]
