# Generated by Django 4.0.6 on 2022-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0015_remove_menu_cart_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
