# Generated by Django 4.0.6 on 2023-01-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0016_alter_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
