# Generated by Django 4.0.6 on 2023-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0020_alter_cart_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
