# Generated by Django 4.0.6 on 2023-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0022_order_remove_cart_order_no_remove_cart_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(),
        ),
    ]
